name: Hello World Example Workflow #

# Controls when the workflow will run
on:
  push: # Triggers the workflow on push events
    branches:
      - main # Only when pushing to the main branch

# A workflow run is made up of one or more jobs
jobs:
  say-hello: # The job ID
    runs-on: ubuntu-latest # The type of machine to run the job on

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the operating system's shell
      - name: Greet the world #
        run: echo "Hello world!" #
